name: Unbelievable Exception
description: "Problema ocorrido com sucesso!"

markdown: pandoc
pygments: true

permalink: /posts/:title
paginate: 5
paginate_path: :num

articles:
  Programação:
    - Shell Script
  Modo Ranheta:
    - Café Azedo
    - AndroiDoctor
  Geral:
    - Dicas

owner:
  name: Marcelo Guimarães
  nickname: Ataxexe
  email: ataxexe@gmail.com
