name: Unbelievable Exception
description: "Exceção ocorrida com sucesso!"

markdown: redcarpet
pygments: true

permalink: /posts/:title
paginate: 10

articles:
  Programação:
    - Shell Script
  Paradigmas:
    - Orientação a Objetos
  Outros:
    - AndroiDoctor
    - Dicas

owner:
  name: Marcelo Guimarães
  nickname: Ataxexe
  email: ataxexe@gmail.com
