name: Unbelievable Exception
description: "Problema ocorrido com sucesso!"

markdown: pandoc
pygments: true

permalink: /posts/:title
paginate: 5
paginate_path: :num

articles:
  Geral:
    - Shell Script
    - Dicas
  Modo Ranheta:
    - Café Azedo
    - Latrina Digital
    - AndroiDoctor

slogans:
  AndroiDoctor: "Faça mais do que trocar a capinha!"
  Latrina Digital: "Dando a descarga naqueles códigos de merda!"
  Café Azedo: "Ragubentices na área de TI!"

url: http://entra.la
download: http://pega.la

owner:
  name: Marcelo Guimarães
  nickname: Ataxexe
  email: ataxexe@gmail.com
