name: Unbelievable Exception
description: "Problema ocorrido com sucesso!"

markdown: pandoc
highlighter: pygments

permalink: /posts/:title
paginate: 15
paginate_path: :num

exclude:
  - build
  - test
  - unbelievable-exception.iml
  - unbelievable-exception.sublime-project
  - unbelievable-exception.sublime-workspace
  - .sass-cache

analytics: true
comments: true
share: true
minify: true

post_categories:
  androidoctor:
    name: AndroiDoctor
    slogan: "Faça mais do que trocar a capinha!"
  latrina digital:
    name: Latrina Digital
    slogan: "Dê a descarga ou jogue no ventilador!"

url: http://entra.la
download: http://downloads.entra.la
github: https://github.com/ataxexe/unbelievable-exception

owner:
  name: Marcelo Guimarães
  nickname: Ataxexe
  email: ataxexe@gmail.com
  contacts:
    GitHub: http://github.com/ataxexe
    YouTube: http://youtube.com/ataxexe
    Google_Plus: http://google.com/+AtaxexeXeréns
    LinkedIn: http://br.linkedin.com/pub/marcelo-guimarães/23/a4/212/
    Twitter: http://twitter.com/ataxexe
